[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::pytest_asyncio.plugin.PytestDeprecationWarning
