"""add grades system

Revision ID: d1d9d890e325
Revises: 0018
Create Date: 2026-07-21 20:38:06.626050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1d9d890e325'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_subjects_school_name')
    )
    op.create_index('ix_subjects_school_id', 'subjects', ['school_id'], unique=False)
    op.create_table('turma_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'turma_id', 'subject_id', 'school_year_id', name='uq_turma_subject_year')
    )
    op.create_index('ix_turma_subjects_school_id', 'turma_subjects', ['school_id'], unique=False)
    op.create_index('ix_turma_subjects_turma_year', 'turma_subjects', ['turma_id', 'school_year_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('trimester', sa.Integer(), nullable=False),
    sa.Column('mac_grade', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('exam_grade', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('final_grade', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exam_grade IS NULL OR (exam_grade >= 0 AND exam_grade <= 20)', name='ck_marks_exam'),
    sa.CheckConstraint('final_grade IS NULL OR (final_grade >= 0 AND final_grade <= 20)', name='ck_marks_final'),
    sa.CheckConstraint('mac_grade  IS NULL OR (mac_grade  >= 0 AND mac_grade  <= 20)', name='ck_marks_mac'),
    sa.CheckConstraint('trimester IN (1, 2, 3)', name='ck_marks_trimester'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'subject_id', 'trimester', name='uq_mark_enrollment_subject_trimester')
    )
    op.create_index('ix_marks_enrollment_id', 'marks', ['enrollment_id'], unique=False)
    op.create_index('ix_marks_school_id', 'marks', ['school_id'], unique=False)
    op.add_column('cash_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('credit_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('credit_refunds', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('credit_refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('documents_library_uploaded_by_fkey', 'documents_library', type_='foreignkey')
    op.create_foreign_key(None, 'documents_library', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.add_column('enrollments', sa.Column('enrollment_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('enrollments', sa.Column('fee_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'invoices', ['fee_invoice_id'], ['id'], ondelete='SET NULL')
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('finance_audit_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('payment_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('photos_uploaded_by_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.add_column('reminder_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_schedules_turma_year', 'schedules', ['school_id', 'turma_id', 'school_year_id'], unique=False)
    op.add_column('schools', sa.Column('wa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('schools', sa.Column('wa_phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('wa_access_token', sa.String(length=500), nullable=True))
    op.alter_column('schools', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CV'::character varying"))
    op.drop_constraint('trip_authorizations_created_by_fkey', 'trip_authorizations', type_='foreignkey')
    op.create_foreign_key(None, 'trip_authorizations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('website_media', 'alt_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('website_media', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('website_pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('website_pages', 'meta_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('website_pages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('website_sections', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('website_sections', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('website_sections', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_website_sections_page_id', table_name='website_sections')
    op.drop_constraint('website_sections_page_id_fkey', 'website_sections', type_='foreignkey')
    op.alter_column('website_settings', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('website_settings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('website_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key('website_sections_page_id_fkey', 'website_sections', 'website_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_website_sections_page_id', 'website_sections', ['page_id'], unique=False)
    op.alter_column('website_sections', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('website_sections', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('website_sections', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('website_pages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('website_pages', 'meta_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('website_pages', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('website_media', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('website_media', 'alt_text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'trip_authorizations', type_='foreignkey')
    op.create_foreign_key('trip_authorizations_created_by_fkey', 'trip_authorizations', 'employees', ['created_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('schools', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CV'::character varying"))
    op.drop_column('schools', 'wa_access_token')
    op.drop_column('schools', 'wa_phone_number_id')
    op.drop_column('schools', 'wa_enabled')
    op.drop_index('ix_schedules_turma_year', table_name='schedules')
    op.drop_column('reminder_logs', 'created_at')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_uploaded_by_fkey', 'photos', 'employees', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('finance_audit_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'fee_invoice_id')
    op.drop_column('enrollments', 'enrollment_fee')
    op.drop_constraint(None, 'documents_library', type_='foreignkey')
    op.create_foreign_key('documents_library_uploaded_by_fkey', 'documents_library', 'employees', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('credit_refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('credit_refunds', 'notes')
    op.alter_column('credit_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cash_sessions', 'created_at')
    op.drop_index('ix_marks_school_id', table_name='marks')
    op.drop_index('ix_marks_enrollment_id', table_name='marks')
    op.drop_table('marks')
    op.drop_index('ix_turma_subjects_turma_year', table_name='turma_subjects')
    op.drop_index('ix_turma_subjects_school_id', table_name='turma_subjects')
    op.drop_table('turma_subjects')
    op.drop_index('ix_subjects_school_id', table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
