"""add grades system

Revision ID: d1d9d890e325
Revises: 0018
Create Date: 2026-07-21 20:38:06.626050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1d9d890e325'
down_revision: Union[str, None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Grade tables are created on the surviving 0021 branch.  Creating them
    # here as well made a clean traversal through the later merge revision
    # fail with DuplicateTableError.
    op.add_column('cash_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('credit_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('credit_refunds', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('credit_refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('documents_library_uploaded_by_fkey', 'documents_library', type_='foreignkey')
    op.create_foreign_key(None, 'documents_library', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.add_column('enrollments', sa.Column('enrollment_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('enrollments', sa.Column('fee_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'invoices', ['fee_invoice_id'], ['id'], ondelete='SET NULL')
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('finance_audit_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('payment_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('photos_uploaded_by_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.add_column('reminder_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_schedules_turma_year', 'schedules', ['school_id', 'turma_id', 'school_year_id'], unique=False)
    op.add_column('schools', sa.Column('wa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('schools', sa.Column('wa_phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('wa_access_token', sa.String(length=500), nullable=True))
    op.alter_column('schools', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CV'::character varying"))
    op.drop_constraint('trip_authorizations_created_by_fkey', 'trip_authorizations', type_='foreignkey')
    op.create_foreign_key(None, 'trip_authorizations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('website_media', 'alt_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('website_media', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('website_pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('website_pages', 'meta_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('website_pages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('website_sections', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('website_sections', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('website_sections', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # This revision branched from 0018 while the website schema continued on
    # the other branch.  Depending on merge order, the index/constraint may
    # already have been removed by 0014.  Fresh installs must support either
    # valid ancestor state.
    op.execute('DROP INDEX IF EXISTS ix_website_sections_page_id')
    op.execute(
        'ALTER TABLE website_sections '
        'DROP CONSTRAINT IF EXISTS website_sections_page_id_fkey'
    )
    op.alter_column('website_settings', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.execute('ALTER TABLE website_settings DROP COLUMN IF EXISTS created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('website_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key('website_sections_page_id_fkey', 'website_sections', 'website_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_website_sections_page_id', 'website_sections', ['page_id'], unique=False)
    op.alter_column('website_sections', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('website_sections', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('website_sections', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('website_pages', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('website_pages', 'meta_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('website_pages', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('website_media', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('website_media', 'alt_text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'trip_authorizations', type_='foreignkey')
    op.create_foreign_key('trip_authorizations_created_by_fkey', 'trip_authorizations', 'employees', ['created_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('schools', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CV'::character varying"))
    op.drop_column('schools', 'wa_access_token')
    op.drop_column('schools', 'wa_phone_number_id')
    op.drop_column('schools', 'wa_enabled')
    op.drop_index('ix_schedules_turma_year', table_name='schedules')
    op.drop_column('reminder_logs', 'created_at')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_uploaded_by_fkey', 'photos', 'employees', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_references', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_plans', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('food_menus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('finance_audit_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'fee_invoice_id')
    op.drop_column('enrollments', 'enrollment_fee')
    op.drop_constraint(None, 'documents_library', type_='foreignkey')
    op.create_foreign_key('documents_library_uploaded_by_fkey', 'documents_library', 'employees', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('credit_refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('credit_refunds', 'notes')
    op.alter_column('credit_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cash_sessions', 'created_at')
    # ### end Alembic commands ###
